name: helm-charts
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  openvasd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: latest
          metrics-enabled: false
      - name: deploy openvasd
        run: |
          helm uninstall openvasd --namespace openvasd|| true
          helm install --namespace openvasd --create-namespace openvasd charts/openvasd/ --values charts/openvasd/values.yaml --values charts/openvasd/mtls-wo-ingress.yaml
          kubectl rollout status --watch --timeout 600s deployment/openvasd --namespace openvasd
      - name: forward port
        run: |
          kubectl --namespace openvasd port-forward deployment/openvasd 8443:443&
      - name: smoketest
        working-directory: rust/smoketest
        env:
          API_KEY: changeme
          OPENVASD_SERVER: https://127.0.0.1:8443
          SCAN_CONFIG: configs/simple_scan_ssh_only.json
          CLIENT_KEY: configs/client_sample.key
          CLIENT_CERT: configs/client_sample.cert
        run: |
          make build run
      - uses: greenbone/actions/helm-build-push@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          chart-name: openvasd
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
